In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import matplotlib as mpl

import requests

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font",family=font_name)

mpl.rcParams["axes.unicode_minus"]= False

# 1. 지역별 없는 업종 파악

In [2]:
import pandas as pd

search = pd.read_csv("C:\\Users\\dbsal\\Desktop\\jeju_data_ver1\\201901-202003.csv")
search.head()

,REG_YYMM,CARD_SIDO_NM,CARD_CCG_NM,STD_CLSS_NM,HOM_SIDO_NM,HOM_CCG_NM,AGE,SEX_CTGO_CD,FLC,CSTMR_CNT,AMT,CNT
0,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,20s,1,1,4,311200,4
1,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,1,2,7,1374500,8
2,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,2,2,6,818700,6
3,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,3,4,1717000,5
4,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,4,3,1047300,3

In [14]:
std_list = search["STD_CLSS_NM"].unique()   #품목(41개)
sido_list = search["CARD_SIDO_NM"].unique() #지역(17개)
check_yymm = [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003] #전체 월(15개)
print(std_list); print(sido_list); print(check_yymm);

['건강보조식품 소매업' '골프장 운영업' '과실 및 채소 소매업' '관광 민예품 및 선물용품 소매업'
 '그외 기타 스포츠시설 운영업' '그외 기타 종합 소매업' '기타 대형 종합 소매업' '기타 외국식 음식점업' '기타 주점업'
 '기타음식료품위주종합소매업' '마사지업' '비알콜 음료점업' '빵 및 과자류 소매업' '서양식 음식점업' '수산물 소매업'
 '슈퍼마켓' '스포츠 및 레크레이션 용품 임대업' '여관업' '욕탕업' '육류 소매업' '일반유흥 주점업' '일식 음식점업'
 '전시 및 행사 대행업' '중식 음식점업' '차량용 가스 충전업' '차량용 주유소 운영업' '체인화 편의점'
 '피자 햄버거 샌드위치 및 유사 음식점업' '한식 음식점업' '호텔업' '화장품 및 방향제 소매업' '휴양콘도 운영업' '여행사업'
 '자동차 임대업' '면세점' '버스 운송업' '택시 운송업' '기타 수상오락 서비스업' '내항 여객 운송업'
 '그외 기타 분류안된 오락관련 서비스업' '정기 항공 운송업']
['강원' '경기' '경남' '경북' '광주' '대구' '대전' '부산' '서울' '세종' '울산' '인천' '전남' '전북'
 '제주' '충남' '충북']
[201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]

In [61]:
#서울 STD_CLSS_NM 품목 list
sido_std_list = search[search["CARD_SIDO_NM"]=='서울']["STD_CLSS_NM"].unique()
#seoul_std_list

In [26]:
empty_std_list = [x for x in std_list if x not in seoul_std_list] #a에는 있고 b에는 없는것
empty_std_list

In [70]:
empty_sido_std_list = [] #지역별 없는 업종 파악변수
for sido in sido_list:
    empty_std_list = [x for x in std_list if x not in search[search["CARD_SIDO_NM"]==sido]["STD_CLSS_NM"].unique()]
    empty_sido_std_list.append([sido, empty_std_list])
    print([sido, empty_std_list])

['강원', ['정기 항공 운송업']]
['경기', ['면세점', '정기 항공 운송업']]
['경남', ['면세점', '정기 항공 운송업']]
['경북', ['면세점', '정기 항공 운송업']]
['광주', ['휴양콘도 운영업', '면세점', '그외 기타 분류안된 오락관련 서비스업', '정기 항공 운송업']]
['대구', ['휴양콘도 운영업', '내항 여객 운송업', '그외 기타 분류안된 오락관련 서비스업', '정기 항공 운송업']]
['대전', ['휴양콘도 운영업', '면세점', '버스 운송업', '택시 운송업', '내항 여객 운송업', '그외 기타 분류안된 오락관련 서비스업', '정기 항공 운송업']]
['부산', ['그외 기타 분류안된 오락관련 서비스업']]
['서울', ['휴양콘도 운영업', '그외 기타 분류안된 오락관련 서비스업']]
['세종', ['호텔업', '휴양콘도 운영업', '여행사업', '자동차 임대업', '면세점', '버스 운송업', '택시 운송업', '내항 여객 운송업', '정기 항공 운송업']]
['울산', ['휴양콘도 운영업', '내항 여객 운송업', '정기 항공 운송업']]
['인천', ['휴양콘도 운영업', '버스 운송업', '그외 기타 분류안된 오락관련 서비스업']]
['전남', ['정기 항공 운송업']]
['전북', ['면세점', '그외 기타 분류안된 오락관련 서비스업']]
['제주', ['버스 운송업']]
['충남', ['면세점']]
['충북', ['그외 기타 분류안된 오락관련 서비스업', '정기 항공 운송업']]

# 2. 업종별 -> 지역별 없는 월이 언제인지 파악

In [104]:
#search_sido_std_reg = search[(search["CARD_SIDO_NM"]=='서울') & (search["STD_CLSS_NM"]=='건강보조식품 소매업')]['REG_YYMM'].unique()

In [113]:
empty_yymm_sido_std = [] #지역별, 품종별, 월별 없는 값
for sido in sido_list: #[지역]
    empty_yymm_std = [] #품종별 월별 없는 값
    for std in std_list: #[품종]
        search_sido_std_reg = search[(search["CARD_SIDO_NM"]==sido) & (search["STD_CLSS_NM"]==std)]['REG_YYMM'].unique() #지역, 품종별 있는 월수에대한 list
        empty_value = [x for x in check_yymm if x not in search_sido_std_reg] #15개월중 없는 년월 찾기
        if empty_value: empty_yymm_std.append([std, empty_value]) #Not empty => 품종, 없는 월수 추가
    empty_yymm_sido_std.append([sido, empty_yymm_std])
    print([sido, empty_yymm_std]) #중간체크하기위한 print - 나중에 삭제

['강원', [['면세점', [201902, 201903, 201905, 201906, 201908, 201909, 201910, 201911, 201912, 202003]], ['버스 운송업', [201902, 202003]], ['택시 운송업', [201911, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['경기', [['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['내항 여객 운송업', [201901, 201902, 201912, 202001, 202002]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201908, 201910, 201911, 201912, 202001, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['경남', [['자동차 임대업', [202003]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['경북', [['여행사업', [201902, 201904, 201909, 201910]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['버스 운송업', [201901, 202003]], ['내항 여객 운송업', [202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201902, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['광주', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['여행사업', [201906, 201908, 201909, 202001, 202003]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['택시 운송업', [201901, 201902, 202002, 202003]], ['기타 수상오락 서비스업', [202003]], ['내항 여객 운송업', [202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['대구', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['여행사업', [201911, 202001, 202002, 202003]], ['면세점', [202003]], ['버스 운송업', [201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['대전', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['여행사업', [201901, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['자동차 임대업', [201911]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['기타 수상오락 서비스업', [201911, 202001, 202002]], ['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['부산', [['내항 여객 운송업', [202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['서울', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['세종', [['관광 민예품 및 선물용품 소매업', [202003]], ['그외 기타 스포츠시설 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202002, 202003]], ['호텔업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['여행사업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['자동차 임대업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['기타 수상오락 서비스업', [201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['울산', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['면세점', [201903, 201908, 201909, 201910, 202001, 202002, 202003]], ['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201911, 202001, 202003]], ['기타 수상오락 서비스업', [202003]], ['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['인천', [['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['자동차 임대업', [201909]], ['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['전남', [['면세점', [202003]], ['택시 운송업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['기타 수상오락 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201903, 201904, 201906, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]
['전북', [['호텔업', [202002]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['버스 운송업', [201904]], ['기타 수상오락 서비스업', [201911, 202003]], ['내항 여객 운송업', [201902, 201903, 201904, 201909, 201910, 201911, 201912, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]

['제주', [['그외 기타 스포츠시설 운영업', [202001, 202002, 202003]], ['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909]], ['기타 수상오락 서비스업', [201901, 201902, 201903, 201905, 201906, 201908, 201909]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906]]]]
['충남', [['자동차 임대업', [201905, 201909]], ['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908]], ['택시 운송업', [201903, 201911, 201912, 202001, 202002, 202003]], ['내항 여객 운송업', [202003]], ['정기 항공 운송업', [202001, 202002, 202003]]]]
['충북', [['여행사업', [201901, 201902, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['자동차 임대업', [202002, 202003]], ['면세점', [201905, 201906, 201907, 201908, 201909, 201911, 202003]], ['버스 운송업', [201902, 201903, 201910, 201911, 201912, 202001, 202002, 202003]], ['내항 여객 운송업', [201901, 201902, 202002, 202003]], ['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]], ['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]]]

In [133]:
check = empty_yymm_sido_std

for sido in check:
    for std in sido:
        for list_ in std:
            print(list_)
    print();print();

강
원
['면세점', [201902, 201903, 201905, 201906, 201908, 201909, 201910, 201911, 201912, 202003]]
['버스 운송업', [201902, 202003]]
['택시 운송업', [201911, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


경
기
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['내항 여객 운송업', [201901, 201902, 201912, 202001, 202002]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201908, 201910, 201911, 201912, 202001, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


경
남
['자동차 임대업', [202003]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


경
북
['여행사업', [201902, 201904, 201909, 201910]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['버스 운송업', [201901, 202003]]
['내항 여객 운송업', [202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201902, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


광
주
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['여행사업', [201906, 201908, 201909, 202001, 202003]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['택시 운송업', [201901, 201902, 202002, 202003]]
['기타 수상오락 서비스업', [202003]]
['내항 여객 운송업', [202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


대
구
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['여행사업', [201911, 202001, 202002, 202003]]
['면세점', [202003]]
['버스 운송업', [201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


대
전
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['여행사업', [201901, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['자동차 임대업', [201911]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['기타 수상오락 서비스업', [201911, 202001, 202002]]
['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


부
산
['내항 여객 운송업', [202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


서
울
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


세
종
['관광 민예품 및 선물용품 소매업', [202003]]
['그외 기타 스포츠시설 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202002, 202003]]
['호텔업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['여행사업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['자동차 임대업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['기타 수상오락 서비스업', [201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


울
산
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['면세점', [201903, 201908, 201909, 201910, 202001, 202002, 202003]]
['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201911, 202001, 202003]]
['기타 수상오락 서비스업', [202003]]
['내항 여객 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


인
천
['휴양콘도 운영업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['자동차 임대업', [201909]]
['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


전
남
['면세점', [202003]]
['택시 운송업', [201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['기타 수상오락 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201903, 201904, 201906, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


전
북
['호텔업', [202002]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['버스 운송업', [201904]]
['기타 수상오락 서비스업', [201911, 202003]]
['내항 여객 운송업', [201902, 201903, 201904, 201909, 201910, 201911, 201912, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]


제
주
['그외 기타 스포츠시설 운영업', [202001, 202002, 202003]]
['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['택시 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909]]
['기타 수상오락 서비스업', [201901, 201902, 201903, 201905, 201906, 201908, 201909]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906]]


충
남
['자동차 임대업', [201905, 201909]]
['면세점', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['버스 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908]]
['택시 운송업', [201903, 201911, 201912, 202001, 202002, 202003]]
['내항 여객 운송업', [202003]]
['정기 항공 운송업', [202001, 202002, 202003]]


충
북
['여행사업', [201901, 201902, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['자동차 임대업', [202002, 202003]]
['면세점', [201905, 201906, 201907, 201908, 201909, 201911, 202003]]
['버스 운송업', [201902, 201903, 201910, 201911, 201912, 202001, 202002, 202003]]
['내항 여객 운송업', [201901, 201902, 202002, 202003]]
['그외 기타 분류안된 오락관련 서비스업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]
['정기 항공 운송업', [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003]]

In [90]:
search2_sido_std.shape

(19570, 12)

# 3. 품목별 2020.1~3월 AMT총합

In [10]:
search2 = search #DF복사
search2 = search2[search2['REG_YYMM'].isin(['202001', '202002', '202003'])] #년월: 2020.1~3월만
search2['AMT_2'] = search2.groupby(['REG_YYMM', 'STD_CLSS_NM']).AMT.transform('sum') #년월, 품목별 그룹 AMT총합
#del search2['AMT_2']
search2 = search2[['STD_CLSS_NM', 'REG_YYMM', 'AMT_2']].drop_duplicates(["AMT_2"]).sort_values(by=['STD_CLSS_NM', 'REG_YYMM']) #AMT_2 index 중복제거
search2.to_csv('C:\\Users\\dbsal\\Desktop\\jeju_data_ver1\\STD_REG_AMTsum.csv',encoding='utf-8-sig', index=False)
search2

C:\Users\dbsal\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

            STD_CLSS_NM  REG_YYMM        AMT_2
20425415     건강보조식품 소매업    202001  10380995655
22098304     건강보조식품 소매업    202002   5340082879
23437284     건강보조식품 소매업    202003   5753676884
20425427        골프장 운영업    202001  13414089759
22098313        골프장 운영업    202002  18228841136
...                 ...       ...          ...
22106336  화장품 및 방향제 소매업    202002  35057136061
23444794  화장품 및 방향제 소매업    202003  31002789304
20436617       휴양콘도 운영업    202001   8873863619
22106375       휴양콘도 운영업    202002   3317926290
23444823       휴양콘도 운영업    202003   1093634463

[123 rows x 3 columns]

In [15]:
# search3 = pd.read_csv("C:\\Users\\dbsal\\Desktop\\jeju_data_ver1\\STD_REG_AMTsum.csv")
# search3

In [66]:
search2
#search2[(search2["STD_CLSS_NM"]=='건강보조식품 소매업') & (search2["REG_YYMM"]=='202001')]
#search2[(search2["STD_CLSS_NM"]=='건강보조식품 소매업')& (search2["REG_YYMM"]==202004)]['AMT_2']

df_test = pd.DataFrame(columns=['STD_CLSS_NM', 'AMT%']) #DF생성
for std in std_list: #품목(41개)
    yymm_202001 = search2[(search2["STD_CLSS_NM"]==std)& (search2["REG_YYMM"]==202001)]['AMT_2'].values[0] if not search2[(search2["STD_CLSS_NM"]==std)& (search2["REG_YYMM"]==202001)].empty else 0
    yymm_202003 = search2[(search2["STD_CLSS_NM"]==std)& (search2["REG_YYMM"]==202003)]['AMT_2'].values[0] if yymm_202001!=0 & (not search2[(search2["STD_CLSS_NM"]==std)& (search2["REG_YYMM"]==202003)].empty) else 0
    print(yymm_202001, yymm_202003, yymm_202003-yymm_202001)
    df_test = df_test.append({'STD_CLSS_NM':std, 'AMT%':((yymm_202003-yymm_202001)/yymm_202001)}, ignore_index=True)

10380995655 5753676884 -4627318771
13414089759 39398851940 25984762181
55612798228 42491078825 -13121719403
981629002 463741220 -517887782
232538575 42628600 -189909975
77895365413 72210158692 -5685206721
517407518399 420628950325 -96778568074
41938280888 29675319516 -12262961372
11372122630 7993009006 -3379113624
113680502895 117569868195 3889365300
1421953223 735895101 -686058122
74922400172 61293487852 -13628912320
59990666287 59099021036 -891645251
117971377072 87416713918 -30554663154
28663677009 19698851610 -8964825399
477500143523 521995396048 44495252525
67670588226 58352181776 -9318406450
16906766618 11160933597 -5745833021
17884794306 6850723890 -11034070416
114895305445 88134048355 -26761257090
36635515403 23863095750 -12772419653
52789878836 37491047321 -15298831515
6569681998 1616742158 -4952939840
65678947057 50520594663 -15158352394
16552241320 14871611495 -1680629825
518733786068 452987251807 -65746534261
341725408491 335570800081 -6154608410
71742418414 65972238656 -5770179758
907512438086 666573459086 -240938979000
19828903792 5073633041 -14755270751
39329126409 31002789304 -8326337105
8873863619 1093634463 -7780229156
7621802855 420268181 -7201534674
2244079460 1893218693 -350860767
30635148449 3933663113 -26701485336
15644764570 5188894134 -10455870436
118323410680 84134752128 -34188658552
95786255 71429085 -24357170
1995967007 1324194320 -671772687
1390350 1580200 189850
41662540376 3314992032 -38347548344

In [65]:
df_test

              STD_CLSS_NM      AMT%
0              건강보조식품 소매업 -0.445749
1                 골프장 운영업  1.937125
2             과실 및 채소 소매업 -0.235948
3       관광 민예품 및 선물용품 소매업 -0.527580
4         그외 기타 스포츠시설 운영업 -0.816682
5            그외 기타 종합 소매업 -0.072985
6            기타 대형 종합 소매업 -0.187045
7             기타 외국식 음식점업 -0.292405
8                  기타 주점업 -0.297140
9           기타음식료품위주종합소매업  0.034213
10                   마사지업 -0.482476
11               비알콜 음료점업 -0.181907
12            빵 및 과자류 소매업 -0.014863
13               서양식 음식점업 -0.259001
14                수산물 소매업 -0.312759
15                   슈퍼마켓  0.093184
16     스포츠 및 레크레이션 용품 임대업 -0.137702
17                    여관업 -0.339854
18                    욕탕업 -0.616953
19                 육류 소매업 -0.232919
20               일반유흥 주점업 -0.348635
21                일식 음식점업 -0.289806
22            전시 및 행사 대행업 -0.753909
23                중식 음식점업 -0.230795
24             차량용 가스 충전업 -0.101535
25            차량용 주유소 운영업 -0.126744
26                체인화 편의점 -0.018010
27  피자 햄버거 샌드위치 및 유사 음식점업 -0.080429
28                한식 음식점업 -0.265494
29                    호텔업 -0.744129
30          화장품 및 방향제 소매업 -0.211709
31               휴양콘도 운영업 -0.876758
32                   여행사업 -0.944860
33                자동차 임대업 -0.156350
34                    면세점 -0.871596
35                 버스 운송업 -0.668330
36                 택시 운송업 -0.288942
37           기타 수상오락 서비스업 -0.254287
38              내항 여객 운송업 -0.336565
39   그외 기타 분류안된 오락관련 서비스업  0.136548
40              정기 항공 운송업 -0.920432

In [51]:
yymm_202001 = search2[(search2["STD_CLSS_NM"]==std)& (search2["REG_YYMM"]==202001)]['AMT_2'].values[0] if not search2[(search2["STD_CLSS_NM"]=='건강보조식품 소매업')& (search2["REG_YYMM"]==202001)].empty else 0
yymm_202001

41662540376

In [22]:
df_test = pd.DataFrame(columns=['STD_CLSS_NM', 'AMT%'])
df_test.append({'STD_CLSS_NM':'STD', 'AMT%':'2'}, ignore_index=True)

  STD_CLSS_NM AMT%
0         STD    2

In [135]:
#search['AMT_2'] = search.groupby(['REG_YYMM', 'CARD_SIDO_NM', 'STD_CLSS_NM']).AMT.transform('sum')

In [155]:
#search.groupby(['REG_YYMM', 'CARD_SIDO_NM', 'STD_CLSS_NM'])
#search.groupby(['REG_YYMM', 'CARD_SIDO_NM', 'STD_CLSS_NM']).sum()

#search.groupby(['REG_YYMM', 'STD_CLSS_NM']).sum().sort_values(by='AMT')
search.groupby(['REG_YYMM', 'STD_CLSS_NM']).sum().sort_values(by='AMT')


test_df = search.groupby(['REG_YYMM', 'STD_CLSS_NM']).sum() #날짜, 품목별 AMT합계

In [167]:
#est_df

In [188]:
test_df2 = test_df.drop(['SEX_CTGO_CD', 'FLC', 'CSTMR_CNT', 'CNT'], axis=1) #필요없는 columns삭제
test_df2

                                         AMT
REG_YYMM STD_CLSS_NM
201901   건강보조식품 소매업               8605074944
         골프장 운영업                 11968748603
         과실 및 채소 소매업             44453112689
         관광 민예품 및 선물용품 소매업         955750428
         그외 기타 분류안된 오락관련 서비스업        1017500
...                                      ...
202003   피자 햄버거 샌드위치 및 유사 음식점업   65972238656
         한식 음식점업                666573459086
         호텔업                      5073633041
         화장품 및 방향제 소매업           31002789304
         휴양콘도 운영업                 1093634463

[615 rows x 1 columns]

In [191]:
please = search[search['REG_YYMM'].isin(['202001', '202002', '202003'])]
please

,REG_YYMM,CARD_SIDO_NM,CARD_CCG_NM,STD_CLSS_NM,HOM_SIDO_NM,HOM_CCG_NM,AGE,SEX_CTGO_CD,FLC,CSTMR_CNT,AMT,CNT
20425415,202001,강원,강릉시,건강보조식품 소매업,강원,강릉시,20s,2,1,3,345000,3
20425416,202001,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,1,2,3,1903450,3
20425417,202001,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,2,2,14,1520500,15
20425418,202001,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,3,9,1239200,9
20425419,202001,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,4,3,606700,4
...,...,...,...,...,...,...,...,...,...,...,...,...
24697787,202003,충북,충주시,휴양콘도 운영업,충북,충주시,30s,1,2,3,43300,4
24697788,202003,충북,충주시,휴양콘도 운영업,충북,충주시,40s,1,3,3,35000,3
24697789,202003,충북,충주시,휴양콘도 운영업,충북,충주시,50s,1,4,4,188000,6
24697790,202003,충북,충주시,휴양콘도 운영업,충북,충주시,50s,2,4,4,99000,6
24697791,202003,충북,충주시,휴양콘도 운영업,충북,충주시,60s,1,5,3,194000,3

In [195]:
mc = please[["STD_CLSS_NM","REG_YYMM","AMT"]].groupby(["STD_CLSS_NM","REG_YYMM"]).sum()
mc.head(10)

                                    AMT
STD_CLSS_NM       REG_YYMM
건강보조식품 소매업        202001    10380995655
                  202002     5340082879
                  202003     5753676884
골프장 운영업           202001    13414089759
                  202002    18228841136
                  202003    39398851940
과실 및 채소 소매업       202001    55612798228
                  202002    34708535677
                  202003    42491078825
관광 민예품 및 선물용품 소매업 202001      981629002

In [196]:
mc[(mc["STD_CLSS_NM"]=='건강보조식품 소매업') & (mc["REG_YYMM"]=='202003')]

KeyError: 'STD_CLSS_NM'

In [187]:
#mc['REG_YYMM']

                             AMT
STD_CLSS_NM REG_YYMM
건강보조식품 소매업  201901    8605074944
            201902    7695979668
            201903    6307887107
            201904    6189621059
            201905    7930621122
...                          ...
휴양콘도 운영업    201911    3333090812
            201912    5293795864
            202001    8873863619
            202002    3317926290
            202003    1093634463

[615 rows x 1 columns]

In [146]:
#del search['AMT_2']
search

,REG_YYMM,CARD_SIDO_NM,CARD_CCG_NM,STD_CLSS_NM,HOM_SIDO_NM,HOM_CCG_NM,AGE,SEX_CTGO_CD,FLC,CSTMR_CNT,AMT,CNT
0,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,20s,1,1,4,311200,4
1,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,1,2,7,1374500,8
2,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,2,2,6,818700,6
3,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,3,4,1717000,5
4,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,4,3,1047300,3
...,...,...,...,...,...,...,...,...,...,...,...,...
24697787,202003,충북,충주시,휴양콘도 운영업,충북,충주시,30s,1,2,3,43300,4
24697788,202003,충북,충주시,휴양콘도 운영업,충북,충주시,40s,1,3,3,35000,3
24697789,202003,충북,충주시,휴양콘도 운영업,충북,충주시,50s,1,4,4,188000,6
24697790,202003,충북,충주시,휴양콘도 운영업,충북,충주시,50s,2,4,4,99000,6
24697791,202003,충북,충주시,휴양콘도 운영업,충북,충주시,60s,1,5,3,194000,3

In [98]:
#결측값 확인
search.isnull().sum()

REG_YYMM             0
CARD_SIDO_NM         0
CARD_CCG_NM      87213
STD_CLSS_NM          0
HOM_SIDO_NM          0
HOM_CCG_NM      147787
AGE                  0
SEX_CTGO_CD          0
FLC                  0
CSTMR_CNT            0
AMT                  0
CNT                  0
dtype: int64